# default config
baseURL = "https://examplesite.org"
languageCode = "ja-jp"
title = "食wave | 日本初の完全食メディア"
theme = "parsa-hugo"
summaryLength = "10"
paginate = 6

# output
[outputs]
home = ["HTML", "RSS", "JSON"]

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/headroom/headroom.js"
[[params.plugins.js]]
link = "plugins/instafeed/instafeed.min.js"
[[params.plugins.js]]
link = "plugins/masonry/masonry.js"
[[params.plugins.js]]
link = "plugins/reading-time/readingTime.min.js"
[[params.plugins.js]]
link = "plugins/smooth-scroll/smooth-scroll.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"

# navigation
[[menu.main]]
name = "About"
URL = "about"
weight = 2

[[menu.main]]
name = "Contact"
URL = "contact"
weight = 3

# deult parameter
[params]
logo_header = "images/logo_header.png"
logo_footer = "images/logo_footer.png"
home = "Home"
# theme layout ( two layout is available, "1" and "2" )
layout = "1"
# Meta data
description = "This is meta description"
# Preloader
preloader = true
# search
search = true
# about author
author = "newt0"
author_image = "images/banner-img.png"
bio = "早大在学中に東大AIスタートアップAidemyにて事業開発部リーダー職を務め、月間売り上げ1000万円増を達成。株式会社ラグナロクにてフォトコンテストアプリ「Camecon」のフロントエンドを担当を経て、2020年にフリーランスエンジニアとして独立。"
# Contact info
# mobile = "+0807621"
email = "kyohei.ito@kernel-dc.jp"
address = "〒113-0033 東京都文京区本郷４丁目１−４ ユニゾ 本郷ビル 3階"
# Contact Form Action
contact_form_action = "#"
# Google Analitycs
google_analitycs_id = "Your ID"
# copyright
copyright = "Copyright &copy; 2020 [newt0](https://kyohei-works.netlify.app/)"

# Instagram feed
[params.instafeed]
enable = true
user_id = "4044026246"
access_token = "4044026246.1677ed0.8896752506ed4402a0519d23b8f50a17"

# social site
[[params.social]]
icon = "ti-facebook"
URL = "https://www.facebook.com/burger.king.you"

[[params.social]]
icon = "ti-twitter-alt"
URL = "https://twitter.com/kyohei_ai"

# [[params.social]]
# icon = "ti-linkedin"
# URL = "#"

[[params.social]]
icon = "ti-github"
URL = "https://github.com/newt0"